package entities.entityss;
// Generated 22/12/2022 04:15:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlumnosNoviembreId generated by hbm2java
 */
@Embeddable
public class AlumnosNoviembreId implements java.io.Serializable {

	private Long idAlumno;
	private String nombreDelAlumno;
	private Short edad;
	private Date fechaDeInscripcion;
	private Long materia;
	private Long maestro;

	public AlumnosNoviembreId() {
	}

	public AlumnosNoviembreId(Long idAlumno, String nombreDelAlumno, Short edad, Date fechaDeInscripcion, Long materia,
			Long maestro) {
		this.idAlumno = idAlumno;
		this.nombreDelAlumno = nombreDelAlumno;
		this.edad = edad;
		this.fechaDeInscripcion = fechaDeInscripcion;
		this.materia = materia;
		this.maestro = maestro;
	}

	@Column(name = "ID_ALUMNO", precision = 10, scale = 0)
	public Long getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Long idAlumno) {
		this.idAlumno = idAlumno;
	}

	@Column(name = "NOMBRE_DEL_ALUMNO", length = 30)
	public String getNombreDelAlumno() {
		return this.nombreDelAlumno;
	}

	public void setNombreDelAlumno(String nombreDelAlumno) {
		this.nombreDelAlumno = nombreDelAlumno;
	}

	@Column(name = "EDAD", precision = 3, scale = 0)
	public Short getEdad() {
		return this.edad;
	}

	public void setEdad(Short edad) {
		this.edad = edad;
	}

	@Column(name = "FECHA_DE_INSCRIPCION", length = 7)
	public Date getFechaDeInscripcion() {
		return this.fechaDeInscripcion;
	}

	public void setFechaDeInscripcion(Date fechaDeInscripcion) {
		this.fechaDeInscripcion = fechaDeInscripcion;
	}

	@Column(name = "MATERIA", precision = 10, scale = 0)
	public Long getMateria() {
		return this.materia;
	}

	public void setMateria(Long materia) {
		this.materia = materia;
	}

	@Column(name = "MAESTRO", precision = 10, scale = 0)
	public Long getMaestro() {
		return this.maestro;
	}

	public void setMaestro(Long maestro) {
		this.maestro = maestro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlumnosNoviembreId))
			return false;
		AlumnosNoviembreId castOther = (AlumnosNoviembreId) other;

		return ((this.getIdAlumno() == castOther.getIdAlumno()) || (this.getIdAlumno() != null
				&& castOther.getIdAlumno() != null && this.getIdAlumno().equals(castOther.getIdAlumno())))
				&& ((this.getNombreDelAlumno() == castOther.getNombreDelAlumno())
						|| (this.getNombreDelAlumno() != null && castOther.getNombreDelAlumno() != null
								&& this.getNombreDelAlumno().equals(castOther.getNombreDelAlumno())))
				&& ((this.getEdad() == castOther.getEdad()) || (this.getEdad() != null && castOther.getEdad() != null
						&& this.getEdad().equals(castOther.getEdad())))
				&& ((this.getFechaDeInscripcion() == castOther.getFechaDeInscripcion())
						|| (this.getFechaDeInscripcion() != null && castOther.getFechaDeInscripcion() != null
								&& this.getFechaDeInscripcion().equals(castOther.getFechaDeInscripcion())))
				&& ((this.getMateria() == castOther.getMateria()) || (this.getMateria() != null
						&& castOther.getMateria() != null && this.getMateria().equals(castOther.getMateria())))
				&& ((this.getMaestro() == castOther.getMaestro()) || (this.getMaestro() != null
						&& castOther.getMaestro() != null && this.getMaestro().equals(castOther.getMaestro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdAlumno() == null ? 0 : this.getIdAlumno().hashCode());
		result = 37 * result + (getNombreDelAlumno() == null ? 0 : this.getNombreDelAlumno().hashCode());
		result = 37 * result + (getEdad() == null ? 0 : this.getEdad().hashCode());
		result = 37 * result + (getFechaDeInscripcion() == null ? 0 : this.getFechaDeInscripcion().hashCode());
		result = 37 * result + (getMateria() == null ? 0 : this.getMateria().hashCode());
		result = 37 * result + (getMaestro() == null ? 0 : this.getMaestro().hashCode());
		return result;
	}

}
