package entities.entityss;
// Generated 22/12/2022 04:15:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alumnos generated by hbm2java
 */
@Entity
@Table(name = "ALUMNOS", schema = "CURSOADMIN")
public class Alumnos implements java.io.Serializable {

	private long idAlumno;
	private Curso curso;
	private String nombreAlumno;
	private Short edad;
	private Date fechaInscripcion;
	private Long maestro;

	public Alumnos() {
	}

	public Alumnos(long idAlumno) {
		this.idAlumno = idAlumno;
	}

	public Alumnos(long idAlumno, Curso curso, String nombreAlumno, Short edad, Date fechaInscripcion, Long maestro) {
		this.idAlumno = idAlumno;
		this.curso = curso;
		this.nombreAlumno = nombreAlumno;
		this.edad = edad;
		this.fechaInscripcion = fechaInscripcion;
		this.maestro = maestro;
	}

	@Id

	@Column(name = "ID_ALUMNO", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(long idAlumno) {
		this.idAlumno = idAlumno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURSO")
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@Column(name = "NOMBRE_ALUMNO", length = 30)
	public String getNombreAlumno() {
		return this.nombreAlumno;
	}

	public void setNombreAlumno(String nombreAlumno) {
		this.nombreAlumno = nombreAlumno;
	}

	@Column(name = "EDAD", precision = 3, scale = 0)
	public Short getEdad() {
		return this.edad;
	}

	public void setEdad(Short edad) {
		this.edad = edad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INSCRIPCION", length = 7)
	public Date getFechaInscripcion() {
		return this.fechaInscripcion;
	}

	public void setFechaInscripcion(Date fechaInscripcion) {
		this.fechaInscripcion = fechaInscripcion;
	}

	@Column(name = "MAESTRO", precision = 10, scale = 0)
	public Long getMaestro() {
		return this.maestro;
	}

	public void setMaestro(Long maestro) {
		this.maestro = maestro;
	}

}
