package entities.entityss;
// Generated 22/12/2022 04:15:31 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatEstados generated by hbm2java
 */
@Entity
@Table(name = "CAT_ESTADOS", schema = "CURSOADMIN")
public class CatEstados implements java.io.Serializable {

	private CatEstadosId id;

	public CatEstados() {
	}

	public CatEstados(CatEstadosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idEstado", column = @Column(name = "ID_ESTADO", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 100)),
			@AttributeOverride(name = "abreviatura", column = @Column(name = "ABREVIATURA", length = 50)) })
	public CatEstadosId getId() {
		return this.id;
	}

	public void setId(CatEstadosId id) {
		this.id = id;
	}

}
