package entities.entityss;
// Generated 22/12/2022 04:15:31 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatRoles generated by hbm2java
 */
@Entity
@Table(name = "CAT_ROLES", schema = "CURSOADMIN")
public class CatRoles implements java.io.Serializable {

	private CatRolesId id;

	public CatRoles() {
	}

	public CatRoles(CatRolesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idRol", column = @Column(name = "ID_ROL", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 100)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 100)) })
	public CatRolesId getId() {
		return this.id;
	}

	public void setId(CatRolesId id) {
		this.id = id;
	}

}
