package entities.entityss;
// Generated 22/12/2022 04:15:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MaestrosNoviembreId generated by hbm2java
 */
@Embeddable
public class MaestrosNoviembreId implements java.io.Serializable {

	private Long idMaestro;
	private String nombreMaestro;
	private Date fechaDeIngreso;

	public MaestrosNoviembreId() {
	}

	public MaestrosNoviembreId(Long idMaestro, String nombreMaestro, Date fechaDeIngreso) {
		this.idMaestro = idMaestro;
		this.nombreMaestro = nombreMaestro;
		this.fechaDeIngreso = fechaDeIngreso;
	}

	@Column(name = "ID_MAESTRO", precision = 10, scale = 0)
	public Long getIdMaestro() {
		return this.idMaestro;
	}

	public void setIdMaestro(Long idMaestro) {
		this.idMaestro = idMaestro;
	}

	@Column(name = "NOMBRE_MAESTRO", length = 30)
	public String getNombreMaestro() {
		return this.nombreMaestro;
	}

	public void setNombreMaestro(String nombreMaestro) {
		this.nombreMaestro = nombreMaestro;
	}

	@Column(name = "FECHA_DE_INGRESO", length = 7)
	public Date getFechaDeIngreso() {
		return this.fechaDeIngreso;
	}

	public void setFechaDeIngreso(Date fechaDeIngreso) {
		this.fechaDeIngreso = fechaDeIngreso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MaestrosNoviembreId))
			return false;
		MaestrosNoviembreId castOther = (MaestrosNoviembreId) other;

		return ((this.getIdMaestro() == castOther.getIdMaestro()) || (this.getIdMaestro() != null
				&& castOther.getIdMaestro() != null && this.getIdMaestro().equals(castOther.getIdMaestro())))
				&& ((this.getNombreMaestro() == castOther.getNombreMaestro())
						|| (this.getNombreMaestro() != null && castOther.getNombreMaestro() != null
								&& this.getNombreMaestro().equals(castOther.getNombreMaestro())))
				&& ((this.getFechaDeIngreso() == castOther.getFechaDeIngreso())
						|| (this.getFechaDeIngreso() != null && castOther.getFechaDeIngreso() != null
								&& this.getFechaDeIngreso().equals(castOther.getFechaDeIngreso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdMaestro() == null ? 0 : this.getIdMaestro().hashCode());
		result = 37 * result + (getNombreMaestro() == null ? 0 : this.getNombreMaestro().hashCode());
		result = 37 * result + (getFechaDeIngreso() == null ? 0 : this.getFechaDeIngreso().hashCode());
		return result;
	}

}
