package entities.entityss;
// Generated 22/12/2022 04:15:31 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MaestrosNoviembre generated by hbm2java
 */
@Entity
@Table(name = "MAESTROS_NOVIEMBRE", schema = "CURSOADMIN")
public class MaestrosNoviembre implements java.io.Serializable {

	private MaestrosNoviembreId id;

	public MaestrosNoviembre() {
	}

	public MaestrosNoviembre(MaestrosNoviembreId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idMaestro", column = @Column(name = "ID_MAESTRO", precision = 10, scale = 0)),
			@AttributeOverride(name = "nombreMaestro", column = @Column(name = "NOMBRE_MAESTRO", length = 30)),
			@AttributeOverride(name = "fechaDeIngreso", column = @Column(name = "FECHA_DE_INGRESO", length = 7)) })
	public MaestrosNoviembreId getId() {
		return this.id;
	}

	public void setId(MaestrosNoviembreId id) {
		this.id = id;
	}

}
