package entities.entityss;
// Generated 22/12/2022 04:15:31 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MateriasNoviembre generated by hbm2java
 */
@Entity
@Table(name = "MATERIAS_NOVIEMBRE", schema = "CURSOADMIN")
public class MateriasNoviembre implements java.io.Serializable {

	private MateriasNoviembreId id;

	public MateriasNoviembre() {
	}

	public MateriasNoviembre(MateriasNoviembreId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "nombreMateria", column = @Column(name = "NOMBRE_MATERIA", length = 30)),
			@AttributeOverride(name = "fechaDeCreacion", column = @Column(name = "FECHA_DE_CREACION", length = 7)),
			@AttributeOverride(name = "idMateria", column = @Column(name = "ID_MATERIA", precision = 10, scale = 0)) })
	public MateriasNoviembreId getId() {
		return this.id;
	}

	public void setId(MateriasNoviembreId id) {
		this.id = id;
	}

}
