package entities.entityss;
// Generated 22/12/2022 04:15:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MateriasNoviembreId generated by hbm2java
 */
@Embeddable
public class MateriasNoviembreId implements java.io.Serializable {

	private String nombreMateria;
	private Date fechaDeCreacion;
	private Long idMateria;

	public MateriasNoviembreId() {
	}

	public MateriasNoviembreId(String nombreMateria, Date fechaDeCreacion, Long idMateria) {
		this.nombreMateria = nombreMateria;
		this.fechaDeCreacion = fechaDeCreacion;
		this.idMateria = idMateria;
	}

	@Column(name = "NOMBRE_MATERIA", length = 30)
	public String getNombreMateria() {
		return this.nombreMateria;
	}

	public void setNombreMateria(String nombreMateria) {
		this.nombreMateria = nombreMateria;
	}

	@Column(name = "FECHA_DE_CREACION", length = 7)
	public Date getFechaDeCreacion() {
		return this.fechaDeCreacion;
	}

	public void setFechaDeCreacion(Date fechaDeCreacion) {
		this.fechaDeCreacion = fechaDeCreacion;
	}

	@Column(name = "ID_MATERIA", precision = 10, scale = 0)
	public Long getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(Long idMateria) {
		this.idMateria = idMateria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MateriasNoviembreId))
			return false;
		MateriasNoviembreId castOther = (MateriasNoviembreId) other;

		return ((this.getNombreMateria() == castOther.getNombreMateria())
				|| (this.getNombreMateria() != null && castOther.getNombreMateria() != null
						&& this.getNombreMateria().equals(castOther.getNombreMateria())))
				&& ((this.getFechaDeCreacion() == castOther.getFechaDeCreacion())
						|| (this.getFechaDeCreacion() != null && castOther.getFechaDeCreacion() != null
								&& this.getFechaDeCreacion().equals(castOther.getFechaDeCreacion())))
				&& ((this.getIdMateria() == castOther.getIdMateria()) || (this.getIdMateria() != null
						&& castOther.getIdMateria() != null && this.getIdMateria().equals(castOther.getIdMateria())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombreMateria() == null ? 0 : this.getNombreMateria().hashCode());
		result = 37 * result + (getFechaDeCreacion() == null ? 0 : this.getFechaDeCreacion().hashCode());
		result = 37 * result + (getIdMateria() == null ? 0 : this.getIdMateria().hashCode());
		return result;
	}

}
