package entities.entityss;
// Generated 22/12/2022 04:15:31 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsuariosAdmin generated by hbm2java
 */
@Entity
@Table(name = "USUARIOS_ADMIN", schema = "CURSOADMIN")
public class UsuariosAdmin implements java.io.Serializable {

	private UsuariosAdminId id;

	public UsuariosAdmin() {
	}

	public UsuariosAdmin(UsuariosAdminId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "ID_USER", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "nombreCompleto", column = @Column(name = "NOMBRE_COMPLETO", length = 100)),
			@AttributeOverride(name = "edad", column = @Column(name = "EDAD", length = 50)),
			@AttributeOverride(name = "direccion", column = @Column(name = "DIRECCION", length = 100)),
			@AttributeOverride(name = "estado", column = @Column(name = "ESTADO", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "rol", column = @Column(name = "ROL", nullable = false, precision = 11, scale = 0)) })
	public UsuariosAdminId getId() {
		return this.id;
	}

	public void setId(UsuariosAdminId id) {
		this.id = id;
	}

}
